class MAIN
{
    public static void main(String[] args)
    {
        System.out.println("My First Java Program.");
        System.out.println("My sunney leone.");
        sout.println("enter a number  of 5 digit.");
        System.out.println("My name is Rajib.");
        // Additional functionality can be added here
        // For example, reading user input or performing calculations
            
    }
}
